server:
  port: 9090

spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: root
    password: root
    hikari:
      driver-class-name: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create-drop